import type { Metadata } from "next";
import "../globals.css";
import { SideMenu } from "@/components/SideMenu";
import { SidebarProvider } from "@/components/ui/sidebar";
import Header from "@/components/Header";

// export const metadata: Metadata = {
//   title: "StockPulse",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider defaultOpen={false}>
      <SideMenu />
      <div className="w-full">
        <Header />
        {children}
      </div>
    </SidebarProvider>
  );
}
